import * as fs from "fs/promises";
import * as path from "path";
import { fileExists, resolveAndGuard } from "@/lib/api";
import { parseWorkspaceConfig } from "./parsers";
import { listProjects } from "./registry";

interface ProjectSummary {
  id: string;
  name: string;
  description: string;
  path: string;
}

const EMPTY = "—";

function nowDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|");
}

async function readWorkspaceName(workspacePath: string): Promise<string> {
  const configPath = resolveAndGuard(workspacePath, ".kyro", "config.json");
  if (!(await fileExists(configPath))) return "Kyro Workspace";
  const content = await fs.readFile(configPath, "utf-8");
  const config = parseWorkspaceConfig(content, workspacePath);
  return config.name || "Kyro Workspace";
}

async function listProjectSummaries(workspacePath: string): Promise<ProjectSummary[]> {
  const registryPath = resolveAndGuard(workspacePath, ".kyro", "projects.json");
  if (!(await fileExists(registryPath))) return [];

  const entries = await listProjects(registryPath);
  return entries.map((entry) => ({
    id: entry.id,
    name: entry.name,
    description: "",
    path: entry.path,
  }));
}

function workspaceReadmeContent(
  workspaceName: string,
  projects: ProjectSummary[]
): string {
  const projectRows = projects.length
    ? projects
        .map(
          (project) =>
            `| ${escapeTable(project.id)} | ${escapeTable(project.name)} | ${escapeTable(project.path)} |`
        )
        .join("\n")
    : `| ${EMPTY} | ${EMPTY} | ${EMPTY} |`;

  return `# ${workspaceName} — Workspace

> Generated by Kyro on ${nowDate()}

---

## Projects Index

| Slug | Name | Path |
|------|------|------|
${projectRows}
`;
}

export function buildDefaultProjectReadmeBody(projectName: string): string {
  const today = nowDate();
  return `# Proyecto: ${projectName}

## Objetivo del Proyecto
Describe aqui el objetivo principal, entregables y criterios de exito.

## Stack Tecnico
- Framework:
- Lenguaje:
- Persistencia:
- Testing:

## Estado Actual
- Sprint activo: _(pendiente)_
- Ultima actualizacion: ${today}
`;
}

export function buildDefaultProjectRoadmap(projectName: string): string {
  return `# ROADMAP — ${projectName}

> Este roadmap es un documento vivo.

## Objetivo
Definir y ejecutar sprints incrementales con trazabilidad de deuda tecnica.

## Sprints

| Sprint | Focus | Status |
|--------|-------|--------|
| 1 | _(definir)_ | pending |

## Reglas

1. Generar un sprint a la vez.
2. La retro del sprint anterior alimenta el siguiente.
3. La deuda tecnica se hereda completa sprint a sprint.
`;
}

export async function syncWorkspaceAgentDocs(workspacePath: string): Promise<void> {
  const workspaceName = await readWorkspaceName(workspacePath);
  const projects = await listProjectSummaries(workspacePath);

  const readmePath = resolveAndGuard(workspacePath, "README.md");
  await fs.writeFile(readmePath, workspaceReadmeContent(workspaceName, projects), "utf-8");
}

/**
 * No-op for external sprint-forge directories.
 * Sprint-forge manages its own RE-ENTRY-PROMPTS.md.
 * Kept as a stub for backward compatibility with callers.
 */
export async function syncProjectReentryPrompts(
  _workspacePath: string,
  _projectId: string,
  _fallbackProjectName?: string
): Promise<void> {
  // External sprint-forge directories manage their own re-entry prompts.
  // Kyro does not write to external directories.
}
